# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('convened', 'Convened'), ('adjourned', 'Adjourned')], default='scheduled', max_length=20)),
                ('quorum_required', models.PositiveSmallIntegerField(default=5)),
                ('attendees', models.JSONField(default=list)),
                ('convened_at', models.DateTimeField(blank=True, null=True)),
                ('adjourned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'committee_meeting',
            },
        ),
        migrations.CreateModel(
            name='NBECMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_sub', models.UUIDField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('member', 'Member'), ('secretary', 'Secretary')], default='member', max_length=20)),
                ('appointment_date', models.DateField()),
                ('tenure_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_voting_member', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'committee_nbecmember',
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('assigned_to_id', models.UUIDField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_items', to='committee.meeting')),
            ],
            options={
                'db_table': 'committee_actionitem',
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('document_ref', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='minutes', to='committee.meeting')),
            ],
            options={
                'verbose_name_plural': 'minutes',
                'db_table': 'committee_minutes',
            },
        ),
        migrations.CreateModel(
            name='ConflictDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_description', models.TextField()),
                ('affected_entity_type', models.CharField(blank=True, max_length=100)),
                ('affected_entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='committee.nbecmember')),
            ],
            options={
                'db_table': 'committee_conflictdeclaration',
            },
        ),
    ]
