# Generated by Django 6.0.5 on 2026-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_fix_nbecmember_is_active_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictdeclaration',
            name='subject_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('item_writer', 'Item Writer'), ('examiner', 'Examiner'), ('supplier', 'Supplier'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
