"""apps/committee/events.py — NBEC Committee event action constants."""

# Member lifecycle
MEMBER_CREATED = "MEMBER_CREATED"
MEMBER_AMENDED = "MEMBER_AMENDED"
MEMBER_ACTIVATED = "MEMBER_ACTIVATED"
MEMBER_EXPIRED = "MEMBER_EXPIRED"
MEMBER_RENEWED = "MEMBER_RENEWED"

# Meeting lifecycle
MEETING_SCHEDULED = "MEETING_SCHEDULED"
MEETING_AGENDA_PUBLISHED = "MEETING_AGENDA_PUBLISHED"
MEETING_ATTENDANCE_RECORDED = "MEETING_ATTENDANCE_RECORDED"
MEETING_CONVENED = "MEETING_CONVENED"
MEETING_ADJOURNED = "MEETING_ADJOURNED"
MEETING_MINUTED = "MEETING_MINUTED"

# Minutes
MINUTES_SIGNED = "MINUTES_SIGNED"
MINUTES_ADDENDUM_ISSUED = "MINUTES_ADDENDUM_ISSUED"
MINUTES_ARCHIVED = "MINUTES_ARCHIVED"
MINUTES_ARCHIVE_FAILED = "MINUTES_ARCHIVE_FAILED"
MINUTES_ARCHIVE_INTEGRITY_MISMATCH = "MINUTES_ARCHIVE_INTEGRITY_MISMATCH"

# Conflict of Interest
COI_DECLARED = "COI_DECLARED"
COI_APPROVED = "COI_APPROVED"
COI_DISMISSED = "COI_DISMISSED"
COI_REFRESH_DUE = "COI_REFRESH_DUE"

# Action items
ACTION_ITEM_CREATED = "ACTION_ITEM_CREATED"
ACTION_ITEM_COMPLETED = "ACTION_ITEM_COMPLETED"
ACTION_ITEM_VERIFIED = "ACTION_ITEM_VERIFIED"
ACTION_ITEM_ESCALATED = "ACTION_ITEM_ESCALATED"
