# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by_id', models.UUIDField()),
                ('sitting_ref', models.CharField(blank=True, max_length=15)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('document_ref', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporting_auditexport',
            },
        ),
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(blank=True, max_length=15)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.JSONField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reporting_kpimetric',
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('snapshot_type', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporting_reportsnapshot',
                'indexes': [models.Index(fields=['sitting_ref', 'snapshot_type'], name='reporting_r_sitting_370942_idx')],
            },
        ),
    ]
