# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sla_type', models.CharField(choices=[('results_publication', 'Results Publication (21-day)'), ('cert_trigger', 'Certificate Trigger (1-hour)'), ('borderline_moderation', 'Borderline Moderation'), ('nlems_response', 'NLEMS Eligibility Response'), ('board_ratification', 'Board Ratification')], max_length=50, unique=True)),
                ('target_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('at_risk_threshold_hours', models.DecimalField(decimal_places=2, help_text='Hours before deadline to trigger At-Risk status', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sla_slaconfig',
            },
        ),
        migrations.CreateModel(
            name='SLAInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('started_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('overdue', 'Overdue'), ('closed', 'Closed')], default='on_track', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='sla.slaconfig')),
            ],
            options={
                'db_table': 'sla_slainstance',
            },
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_status', models.CharField(max_length=20)),
                ('escalated_to', models.JSONField(default=list)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('sla_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='sla.slainstance')),
            ],
            options={
                'db_table': 'sla_slaescalation',
            },
        ),
        migrations.AddIndex(
            model_name='slainstance',
            index=models.Index(fields=['status', 'deadline'], name='sla_slainst_status_35df39_idx'),
        ),
    ]
