# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.db.models.deletion
import shared.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('ref', models.CharField(help_text='Format: BAR-YYYY-MM e.g. BAR-2026-05', max_length=15, primary_key=True, serialize=False, validators=[shared.validators.validate_sitting_ref])),
                ('sitting_date', models.DateField()),
                ('sitting_end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('locked', 'Locked'), ('active', 'Active (Sitting in Progress)'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('normalisation_method', models.CharField(blank=True, max_length=30)),
                ('created_by_id', models.UUIDField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sitting_sitting',
            },
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint', to='sitting.sitting')),
            ],
            options={
                'db_table': 'sitting_blueprint',
            },
        ),
        migrations.CreateModel(
            name='SittingLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.CharField(default='system', max_length=20)),
                ('override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('sitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock_record', to='sitting.sitting')),
            ],
            options={
                'db_table': 'sitting_sittinglock',
            },
        ),
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=255)),
                ('total_marks', models.PositiveSmallIntegerField(default=100)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=180)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_papers', to='sitting.sitting')),
            ],
            options={
                'db_table': 'sitting_subjectpaper',
                'unique_together': {('sitting', 'subject_code')},
            },
        ),
    ]
