# Generated by Django 6.0.5 on 2026-05-21 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitting',
            name='approved_via_meeting_id',
            field=models.UUIDField(blank=True, help_text='Phase 2 Meeting that approved the configuration (pre-lock).', null=True),
        ),
        migrations.AddField(
            model_name='sitting',
            name='centres',
            field=models.JSONField(blank=True, default=list, help_text='List of centre refs available for this sitting.'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='compensated_aggregate_floor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aggregate floor across papers for a compensated pass (F03-02).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sitting',
            name='compensated_min_per_paper',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum mark per paper for a compensated pass (F03-02).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sitting',
            name='pass_band_max',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='NBEC policy band — maximum permissible per-paper pass standard.', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitting',
            name='pass_band_min',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='NBEC policy band — minimum permissible per-paper pass standard.', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitting',
            name='pass_rule',
            field=models.CharField(choices=[('all_pass', 'All papers individually pass'), ('aggregate', 'Aggregate threshold'), ('compensated', 'Compensated pass with cap')], default='all_pass', max_length=20),
        ),
        migrations.AddField(
            model_name='subjectpaper',
            name='mode',
            field=models.CharField(choices=[('cbt', 'Computer-Based Testing'), ('pbt', 'Paper-Based Testing'), ('hybrid', 'Hybrid')], default='cbt', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectpaper',
            name='normalisation_method',
            field=models.CharField(choices=[('none', 'None'), ('linear', 'Linear'), ('equipercentile', 'Equipercentile'), ('bespoke', 'NBEC-bespoke')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='subjectpaper',
            name='normalisation_params',
            field=models.JSONField(blank=True, default=dict, help_text='Method-specific parameters; frozen at T-30 lock.'),
        ),
        migrations.AddField(
            model_name='subjectpaper',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='[{name, marks, time_minutes}] — section marks must sum to total_marks.'),
        ),
        migrations.CreateModel(
            name='BlueprintVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('version_no', models.PositiveIntegerField()),
                ('topic_coverage', models.JSONField(default=dict)),
                ('cognitive_distribution', models.JSONField(default=dict)),
                ('difficulty_distribution', models.JSONField(default=dict)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('total_marks', models.PositiveSmallIntegerField(default=100)),
                ('tolerance', models.DecimalField(decimal_places=3, default=0.05, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sitting_blueprintversion',
                'ordering': ['subject_code', '-version_no'],
                'unique_together': {('subject_code', 'version_no')},
            },
        ),
        migrations.AddField(
            model_name='subjectpaper',
            name='blueprint_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_papers', to='sitting.blueprintversion'),
        ),
        migrations.CreateModel(
            name='SittingLockEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('auto_lock', 'Auto T-30 Lock'), ('chair_amend', 'Chair Non-Critical Amendment'), ('resolution_amend', 'NBEC Resolution Amendment')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, help_text='Keycloak sub of the actor; null for system-fired auto-lock.', null=True)),
                ('justification', models.TextField(blank=True)),
                ('resolution_ref', models.CharField(blank=True, help_text='NBEC resolution / minutes reference for resolution_amend.', max_length=100)),
                ('affected_fields', models.JSONField(blank=True, default=list)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_events', to='sitting.sitting')),
            ],
            options={
                'db_table': 'sitting_sittinglockevent',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_no', models.PositiveIntegerField()),
                ('seed', models.BigIntegerField(help_text='Deterministic generator seed.')),
                ('items', models.JSONField(default=list, help_text='Ordered list of item ids (UUIDs as strings).')),
                ('item_order', models.JSONField(blank=True, default=dict, help_text='Per-item option-order map for MCQ randomisation.')),
                ('coverage_report', models.JSONField(blank=True, default=dict)),
                ('failed_constraints', models.JSONField(blank=True, default=list)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('passed', 'Passed'), ('failed', 'Failed Coverage Check')], default='pending', max_length=10)),
                ('generated_by_id', models.UUIDField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sitting.subjectpaper')),
            ],
            options={
                'db_table': 'sitting_variant',
                'ordering': ['paper', 'variant_no'],
                'unique_together': {('paper', 'variant_no')},
            },
        ),
    ]
