# Generated by Django 6.0.5 on 2026-05-21 01:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=50)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_limit', models.IntegerField()),
                ('item_ids', models.JSONField(default=list)),
                ('variants', models.JSONField(default=list)),
                ('blueprint_ref', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('essay', 'Essay'), ('short_answer', 'Short Answer'), ('practical', 'Practical'), ('multiple_response', 'Multiple Response')], default='mcq', max_length=50, verbose_name='Item Type')),
                ('current_version_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('blueprint_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('cognitive_level', models.CharField(blank=True, max_length=50, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authored_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('justification', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='itembank.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('facility_index', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('discrimination_index', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='itembank.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('content', models.TextField()),
                ('metadata_snapshot', models.JSONField()),
                ('asset_refs', models.JSONField(default=list)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='itembank.item')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_path', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='itembank.itemversion')),
            ],
        ),
        migrations.CreateModel(
            name='PanelVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50)),
                ('justification', models.TextField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_votes', to='itembank.item')),
                ('panellist_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'panel_vote',
            },
        ),
        migrations.CreateModel(
            name='VaultAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('read', 'Read'), ('export', 'Export')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itembank.item')),
            ],
        ),
        migrations.CreateModel(
            name='VaultExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Executed', 'Executed'), ('Expired', 'Expired')], default='Pending', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cosigner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cosigned_exports', to=settings.AUTH_USER_MODEL)),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_export_request',
            },
        ),
        migrations.AddConstraint(
            model_name='itemversion',
            constraint=models.UniqueConstraint(fields=('item_id', 'version_no'), name='unique_item_version_per_item'),
        ),
        migrations.AlterUniqueTogether(
            name='panelvote',
            unique_together={('item_id', 'panellist_id')},
        ),
    ]
