# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('multiple_response', 'Multiple Response'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('practical', 'Practical')], max_length=30)),
                ('content_encrypted', models.BinaryField(blank=True, null=True)),
                ('vault_nonce', models.BinaryField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('status', django_fsm.FSMField(default='draft', max_length=50, protected=True)),
                ('author_id', models.UUIDField()),
                ('reviewer_id', models.UUIDField(blank=True, null=True)),
                ('audit_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'itembank_item',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('blueprint_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'itembank_exampaper',
                'unique_together': {('sitting_ref', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='itembank.item')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_usages', to='itembank.exampaper')),
            ],
            options={
                'db_table': 'itembank_itemusage',
            },
        ),
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('changed_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='itembank.item')),
            ],
            options={
                'db_table': 'itembank_itemversion',
                'ordering': ['-version'],
                'unique_together': {('item', 'version')},
            },
        ),
    ]
