# Generated by Django 6.0.5 on 2026-05-20 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemversion',
            options={'ordering': ['-version_no']},
        ),
        migrations.AlterField(
            model_name='panelvote',
            name='vote',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vaultexportrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Executed', 'Executed'), ('Expired', 'Expired')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='itemversion',
            unique_together={('item_id', 'version_no')},
        ),
        migrations.AlterUniqueTogether(
            name='panelvote',
            unique_together={('item_id', 'panellist_id')},
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='itemcomment',
            table='item_comment',
        ),
        migrations.AlterModelTable(
            name='itemversion',
            table='item_version',
        ),
        migrations.AlterModelTable(
            name='panelvote',
            table='panel_vote',
        ),
        migrations.AlterModelTable(
            name='vaultexportrequest',
            table='vault_export_request',
        ),
    ]
