# Generated by Django 6.0.5 on 2026-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cognitive_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
