# Generated by Django 6.0.5 on 2026-05-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Reviewed', 'Reviewed'), ('Revised', 'Revised'), ('Moderation Panel', 'Moderation Panel'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Locked for Use', 'Locked for Use')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemtransition',
            name='from_state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Reviewed', 'Reviewed'), ('Revised', 'Revised'), ('Moderation Panel', 'Moderation Panel'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Locked for Use', 'Locked for Use')], max_length=50),
        ),
        migrations.AlterField(
            model_name='itemtransition',
            name='to_state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Reviewed', 'Reviewed'), ('Revised', 'Revised'), ('Moderation Panel', 'Moderation Panel'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Locked for Use', 'Locked for Use')], max_length=50),
        ),
    ]
