# Generated by Django 6.0.5 on 2026-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0002_alter_itemversion_options_alter_panelvote_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultexportrequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
