# Generated by Django 6.0.5 on 2026-05-20 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0002_alter_item_cognitive_level_alter_item_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemversion',
            constraint=models.UniqueConstraint(fields=('item_id', 'version_no'), name='unique_item_version_per_item'),
        ),
    ]
