# Generated by Django 6.0.5 on 2026-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembank', '0003_item_quality_flagged_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='candidate_count',
            field=models.IntegerField(default=0, help_text='Number of candidates who saw this item in the referenced sitting.'),
        ),
        migrations.AddField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='blueprint_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cognitive_level',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='difficulty',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='True if item has underperformed across two sittings and requires moderator review'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Reviewed', 'Reviewed'), ('Revised', 'Revised'), ('Moderation Panel', 'Moderation Panel'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Locked for Use', 'Locked for Use')], db_index=True, default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemusage',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='itemusage',
            name='sitting_ref',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='blueprint_ref',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='sitting_ref',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Constructed', 'Constructed'), ('Ready For Approval', 'Ready For Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft', max_length=50),
        ),
    ]
