apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbes-redis
  namespace: nbes
  labels:
    app.kubernetes.io/name: nbes-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbes-redis
  template:
    metadata:
      labels:
        app: nbes-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nbes-redis-svc
  namespace: nbes
  labels:
    app.kubernetes.io/name: nbes-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: nbes-redis
