# Generated by Django 6.0.5 on 2026-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpanel',
            name='default_config',
            field=models.JSONField(blank=True, default=dict, help_text='Frontend-only — initial filters, layout hints, etc.'),
        ),
        migrations.AlterField(
            model_name='dashboardpanel',
            name='panel_key',
            field=models.CharField(db_index=True, help_text='Stable identifier the frontend keys on, e.g. examiner.marking_queue.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboardpanel',
            name='role_codename',
            field=models.CharField(db_index=True, help_text='Name of the NBES Role this panel belongs to (matches ``users.Role.name``).', max_length=80),
        ),
    ]
