# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertTriggerRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('result_ref', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired — Awaiting Acknowledgement'), ('acknowledged', 'Acknowledged by System 14'), ('failed', 'Failed — Retrying'), ('sla_breached', 'SLA Breached')], default='pending', max_length=20)),
                ('webhook_payload', models.JSONField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_ref', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cert_triggers', to='registration.candidate')),
            ],
            options={
                'db_table': 'cert_trigger_certtriggerrecord',
                'indexes': [models.Index(fields=['status', 'sla_deadline'], name='cert_trigge_status_675a4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PassRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('index_number', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=255)),
                ('pass_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pass_records', to='registration.candidate')),
            ],
            options={
                'db_table': 'cert_trigger_passrecord',
                'unique_together': {('candidate', 'sitting_ref')},
            },
        ),
    ]
