# Generated by Django 6.0.5 on 2026-05-19 12:43

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('sitting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('cbt', 'CBT'), ('pbt', 'PBT')], max_length=10)),
                ('script_ref', models.CharField(max_length=50, unique=True)),
                ('status', django_fsm.FSMField(default='received', max_length=50, protected=True)),
                ('borderline_flagged', models.BooleanField(default=False)),
                ('reconciliation_required', models.BooleanField(default=False)),
                ('audit_hash', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='registration.registration')),
                ('subject_paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='sitting.subjectpaper')),
            ],
            options={
                'db_table': 'marking_script',
            },
        ),
        migrations.CreateModel(
            name='MarkingDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('ai_rubric_breakdown', models.JSONField(blank=True, null=True)),
                ('moderator_id', models.UUIDField(blank=True, null=True)),
                ('moderator_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('justification', models.TextField(blank=True)),
                ('second_marker_id', models.UUIDField(blank=True, null=True)),
                ('second_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('arbitration_outcome', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('arbitration_rationale', models.TextField(blank=True)),
                ('final_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('audit_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_decision', to='marking.script')),
            ],
            options={
                'db_table': 'marking_markingdecision',
            },
        ),
        migrations.CreateModel(
            name='DoubleMarkSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('second_marker_id', models.UUIDField()),
                ('sampled_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='double_mark', to='marking.script')),
            ],
            options={
                'db_table': 'marking_doublemarksample',
            },
        ),
    ]
