# Generated by Django 6.0.5 on 2026-05-18 19:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_sub', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='invited', max_length=20)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('mfa_enrolled', models.BooleanField(default=False)),
                ('invite_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'users_userprofile',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(db_index=True, max_length=128)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.userprofile')),
            ],
            options={
                'db_table': 'users_session',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='users.userprofile')),
            ],
            options={
                'db_table': 'users_passwordhistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFAEnrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_type', models.CharField(choices=[('totp', 'TOTP'), ('webauthn', 'WebAuthn / FIDO2'), ('sms', 'SMS OTP')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('credential_ref', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_enrolments', to='users.userprofile')),
            ],
            options={
                'db_table': 'users_mfaenrolment',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_attempted', models.EmailField(blank=True, max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('bad_credential', 'Bad Credential'), ('account_locked', 'Account Locked'), ('unknown_user', 'Unknown User'), ('mfa_fail', 'MFA Failed'), ('ip_throttled', 'IP Throttled')], max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to='users.userprofile')),
            ],
            options={
                'db_table': 'users_loginattempt',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['status'], name='users_userp_status_b3f50f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='users_userp_role_c31a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'revoked_at'], name='users_sessi_user_id_8629ba_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires_at'], name='users_sessi_expires_16cf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='mfaenrolment',
            index=models.Index(fields=['user', 'factor_type'], name='users_mfaen_user_id_f90156_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip', 'occurred_at'], name='users_login_ip_b211df_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user', 'occurred_at'], name='users_login_user_id_77cc6c_idx'),
        ),
    ]
