# Generated by Django 4.2.30 on 2026-05-25 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_roles_and_seed(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    UserProfile = apps.get_model("users", "UserProfile")
    UserRole = apps.get_model("users", "UserRole")
    RoleChangeEvent = apps.get_model("users", "RoleChangeEvent")
    
    roles_data = [
        ("system_administrator", "NBES System Administrator", True),
        ("nbec_member", "NBEC Member", True),
        ("nbec_secretariat", "NBEC Secretariat", True),
        ("item_writer", "Item Writer", True),
        ("moderator", "Moderator", True),
        ("examiner", "Examiner", True),
        ("candidate", "Candidate", False),
        ("clet_registrar", "CLET Registrar", True),
        ("invigilator", "Invigilator", True),
        ("centre_coordinator", "Centre Coordinator", True),
        ("remote_proctor", "Remote Proctor", True),
        ("dti_operations", "DTI Operations", True),
        ("service_desk_agent", "Service Desk Agent", True),
        ("auditor", "Auditor", True),
        ("director_general", "Director General", True),
    ]
    
    db_roles = {}
    for name, desc, is_internal in roles_data:
        role_obj, _ = Role.objects.get_or_create(
            name=name,
            defaults={"description": desc, "is_custom": False}
        )
        role_obj.is_internal = is_internal
        role_obj.save()
        db_roles[name] = role_obj

    from django.utils import timezone
    today = timezone.now().date()
    now_ts = timezone.now()
    
    for profile in UserProfile.objects.all():
        if profile.keycloak_sub:
            profile.status = "active"
        else:
            profile.status = "pending_invite"
        profile.save()
        
        old_role_name = getattr(profile, "role", "").strip()
        if old_role_name:
            norm_name = old_role_name.lower().replace("-", "_")
            role_obj = db_roles.get(norm_name)
            if not role_obj:
                role_obj, _ = Role.objects.get_or_create(
                    name=norm_name,
                    defaults={"description": f"Custom role {old_role_name}", "is_custom": True}
                )
            
            effective_date = profile.created_at.date() if profile.created_at else today
            UserRole.objects.get_or_create(
                user=profile,
                role=role_obj,
                defaults={
                    "effective_from": effective_date,
                    "created_at": profile.created_at or now_ts
                }
            )
            RoleChangeEvent.objects.get_or_create(
                user=profile,
                role=role_obj,
                change_type="assign",
                defaults={
                    "occurred_at": profile.created_at or now_ts
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_paper_search_codenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='Internal roles require MFA. Candidate is the only external role.'),
        ),
        migrations.AddField(
            model_name='role',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented on permission matrix changes for this role.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible fields: national_id, department, phone, etc.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending_invite', 'Pending Invite'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending_invite', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='keycloak_sub',
            field=models.UUIDField(blank=True, db_index=True, help_text='IAM subject identifier. Null until IAM provisioning completes.', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null = open-ended assignment', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to='users.userprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.userprofile')),
            ],
            options={
                'db_table': 'users_userrole',
            },
        ),
        migrations.CreateModel(
            name='RoleChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('assign', 'Assigned'), ('revoke', 'Revoked')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to='users.userprofile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_events', to='users.userprofile')),
            ],
            options={
                'db_table': 'users_rolechangeevent',
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role'), name='unique_active_user_role'),
        ),
        migrations.AddIndex(
            model_name='rolechangeevent',
            index=models.Index(fields=['user', 'occurred_at'], name='users_rolec_user_id_d4e79a_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechangeevent',
            index=models.Index(fields=['role', 'occurred_at'], name='users_rolec_role_id_0a5ef0_idx'),
        ),
        migrations.RunPython(migrate_roles_and_seed, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
