# Generated by Django 6.0.5 on 2026-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bulkimportrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleassignmentapproval',
            new_name='users_rolea_status_538550_idx',
            old_name='users_roleap_status_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='roleassignmentapproval',
            new_name='users_rolea_target__c3ebeb_idx',
            old_name='users_roleap_target_sta_idx',
        ),
        migrations.AddField(
            model_name='roleassignmentapproval',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
