"""apps/sitting/events.py — Phase 4 Sitting event action constants."""

# Sitting lifecycle
SITTING_CREATED = "SITTING_CREATED"
SITTING_DRAFT_UPDATED = "SITTING_DRAFT_UPDATED"
SITTING_CONFIGURED = "SITTING_CONFIGURED"
SITTING_APPROVED = "SITTING_APPROVED"
SITTING_LOCKED = "SITTING_LOCKED"
SITTING_AMENDED_CHAIR = "SITTING_AMENDED_CHAIR"
SITTING_AMENDED_RESOLUTION = "SITTING_AMENDED_RESOLUTION"
SITTING_ACTIVATED = "SITTING_ACTIVATED"
SITTING_CLOSED = "SITTING_CLOSED"

# SubjectPaper lifecycle
PAPER_ADDED = "PAPER_ADDED"
PAPER_UPDATED = "PAPER_UPDATED"
PAPER_REMOVED = "PAPER_REMOVED"

# Blueprint lifecycle
BLUEPRINT_VERSION_PUBLISHED = "BLUEPRINT_VERSION_PUBLISHED"

# Variant lifecycle
VARIANT_GENERATED = "VARIANT_GENERATED"
VARIANT_VALIDATED = "VARIANT_VALIDATED"
VARIANT_REJECTED = "VARIANT_REJECTED"

# T-30 reminders
T30_REMINDER_SENT = "T30_REMINDER_SENT"
