# Generated by Django 6.0.5 on 2026-05-19 12:43

import django.db.models.deletion
import django_fsm
import shared.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_sub', models.UUIDField(db_index=True, unique=True)),
                ('index_number', models.CharField(blank=True, help_text='Assigned on confirmed registration. Format: BAR-YYYY-CCCCC', max_length=15, null=True, unique=True, validators=[shared.validators.validate_index_number])),
                ('surname', models.CharField(max_length=150)),
                ('given_names', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=30, unique=True)),
                ('llb_id', models.CharField(max_length=50)),
                ('lpt_cert_number', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20, validators=[shared.validators.validate_ghana_phone])),
                ('photograph_ref', models.TextField(blank=True)),
                ('eligibility_status', models.CharField(choices=[('pending', 'Pending Verification'), ('eligible', 'Eligible'), ('blocked', 'Blocked — Ineligible'), ('eligible_override', 'Eligible (DG Override)')], default='pending', max_length=30)),
                ('disability_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_candidate',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('status', django_fsm.FSMField(default='draft', max_length=50, protected=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('block_reason', models.TextField(blank=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registration.candidate')),
            ],
            options={
                'db_table': 'registration_registration',
                'unique_together': {('candidate', 'sitting_ref')},
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(blank=True, max_length=30)),
                ('nlems_response', models.JSONField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='registration.registration')),
            ],
            options={
                'db_table': 'registration_eligibilitycheck',
            },
        ),
        migrations.CreateModel(
            name='RegistrationSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slip_ref', models.CharField(max_length=50, unique=True)),
                ('document_ref', models.TextField(blank=True)),
                ('qr_data', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slip', to='registration.registration')),
            ],
            options={
                'db_table': 'registration_registrationslip',
            },
        ),
    ]
