# Generated by Django 6.0.5 on 2026-05-19 12:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('source_system', models.CharField(default='nbes', max_length=20)),
                ('chain_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'db_table': 'audit_auditevent',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_outboxevent',
                'indexes': [models.Index(fields=['published', 'created_at'], name='audit_outbo_publish_d19fd4_idx')],
            },
        ),
    ]
