# Generated by Django 6.0.5 on 2026-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='entity_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION audit_event_no_update_delete()
            RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'audit_auditevent is append-only';
            END;
            $$ LANGUAGE plpgsql;

            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM pg_trigger WHERE tgname = 'audit_event_block_update'
              ) THEN
                CREATE TRIGGER audit_event_block_update
                  BEFORE UPDATE ON audit_auditevent
                  FOR EACH ROW EXECUTE FUNCTION audit_event_no_update_delete();
              END IF;

              IF NOT EXISTS (
                SELECT 1 FROM pg_trigger WHERE tgname = 'audit_event_block_delete'
              ) THEN
                CREATE TRIGGER audit_event_block_delete
                  BEFORE DELETE ON audit_auditevent
                  FOR EACH ROW EXECUTE FUNCTION audit_event_no_update_delete();
              END IF;
            END;
            $$;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS audit_event_block_update ON audit_auditevent;
            DROP TRIGGER IF EXISTS audit_event_block_delete ON audit_auditevent;
            DROP FUNCTION IF EXISTS audit_event_no_update_delete();
            """,
        ),
    ]
