# Generated by Django 6.0.5 on 2026-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_securityevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='audit_secur_categor_cedfec_idx',
            old_name='audit_secev_cat_occ_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='audit_secur_ip_addr_e620d8_idx',
            old_name='audit_secev_ip_occ_idx',
        ),
        migrations.AlterField(
            model_name='dailyhashanchor',
            name='anchor_ref',
            field=models.CharField(blank=True, default='', help_text='Receipt id returned by System 22 once notarisation completes.', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyhashanchor',
            name='event_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of AuditEvent rows produced on this UTC day.'),
        ),
        migrations.AlterField(
            model_name='dailyhashanchor',
            name='head_event_id',
            field=models.UUIDField(blank=True, help_text='event_id of the last AuditEvent on this UTC day.', null=True),
        ),
        migrations.AlterField(
            model_name='dailyhashanchor',
            name='head_hash',
            field=models.CharField(help_text="SHA-256 chain hash of the day's last event. The anchor.", max_length=64),
        ),
        migrations.AlterField(
            model_name='dailyhashanchor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='indicators',
            field=models.JSONField(default=dict, help_text='Free-form details: path, method, role names, reason, etc.'),
        ),
    ]
