# Generated by Django 6.0.5 on 2026-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_rename_audit_secev_cat_occ_idx_audit_secur_categor_cedfec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
