# Generated by Django 6.0.5 on 2026-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_outboxevent_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='category',
            field=models.CharField(choices=[('auth_token_invalid', 'auth_token_invalid'), ('auth_token_expired', 'auth_token_expired'), ('auth_audience_mismatch', 'auth_audience_mismatch'), ('authz_denied', 'authz_denied'), ('step_up_denied', 'step_up_denied'), ('throttle_applied', 'throttle_applied'), ('ip_blocked', 'ip_blocked'), ('anomaly_detected', 'anomaly_detected')], db_index=True, max_length=40),
        ),
    ]
