import uuid
from django.db import migrations, models


def partition_audit_event_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    # 1. Rename old table
    schema_editor.execute("ALTER TABLE audit_auditevent RENAME TO audit_auditevent_old;")

    # 2. Drop old triggers on renamed table
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_event_block_update ON audit_auditevent_old;")
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_event_block_delete ON audit_auditevent_old;")
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_auditevent_no_update ON audit_auditevent_old;")
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_auditevent_no_delete ON audit_auditevent_old;")

    # 3. Recreate table with single-column PK on id so Django ORM pk lookups
    # work correctly. A composite PK (created_at, id) would drift from the
    # model's BigAutoField(primary_key=True) declaration.
    schema_editor.execute("""
        CREATE TABLE audit_auditevent (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            event_id uuid NOT NULL,
            actor_id uuid,
            action varchar(100) NOT NULL,
            entity_type varchar(100) NOT NULL DEFAULT '',
            entity_id varchar(64),
            old_state jsonb,
            new_state jsonb,
            ip_address inet,
            user_agent text NOT NULL,
            request_id uuid,
            source_system varchar(20) NOT NULL DEFAULT 'nbes',
            chain_hash varchar(64) NOT NULL,
            created_at timestamptz NOT NULL,
            PRIMARY KEY (id)
        );
    """)

    # 4. Index on event_id (non-unique, matches AlterField in this migration)
    schema_editor.execute("""
        CREATE INDEX audit_auditevent_event_id_idx ON audit_auditevent (event_id);
    """)

    # 5. Index on entity_id
    schema_editor.execute("""
        CREATE INDEX audit_auditevent_entity_id_idx ON audit_auditevent (entity_id);
    """)

    # 6. Index on created_at for time-range queries
    schema_editor.execute("""
        CREATE INDEX audit_auditevent_created_at_idx ON audit_auditevent (created_at);
    """)

    # 7. Copy data from old table
    schema_editor.execute("""
        INSERT INTO audit_auditevent (
            id, event_id, actor_id, action, entity_type, entity_id,
            old_state, new_state, ip_address, user_agent, request_id,
            source_system, chain_hash, created_at
        )
        SELECT
            id, event_id, actor_id, action, entity_type, entity_id,
            old_state, new_state, ip_address, user_agent, request_id,
            source_system, chain_hash, created_at
        FROM audit_auditevent_old;
    """)

    # 8. Align identity sequence
    schema_editor.execute("""
        SELECT setval(pg_get_serial_sequence('audit_auditevent', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM audit_auditevent;
    """)

    # 9. Drop old table
    schema_editor.execute("DROP TABLE audit_auditevent_old;")

    # 10. Recreate block mutations triggers on the partitioned table
    schema_editor.execute("""
        CREATE TRIGGER audit_auditevent_no_update
        BEFORE UPDATE ON audit_auditevent
        FOR EACH ROW EXECUTE FUNCTION audit_auditevent_block_mutations();
    """)
    schema_editor.execute("""
        CREATE TRIGGER audit_auditevent_no_delete
        BEFORE DELETE ON audit_auditevent
        FOR EACH ROW EXECUTE FUNCTION audit_auditevent_block_mutations();
    """)


def unpartition_audit_event_postgresql(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    # 1. Rename partitioned table
    schema_editor.execute("ALTER TABLE audit_auditevent RENAME TO audit_auditevent_old;")

    # 2. Drop triggers on renamed table
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_auditevent_no_update ON audit_auditevent_old;")
    schema_editor.execute("DROP TRIGGER IF EXISTS audit_auditevent_no_delete ON audit_auditevent_old;")

    # 3. Recreate standard table
    schema_editor.execute("""
        CREATE TABLE audit_auditevent (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            event_id uuid NOT NULL,
            actor_id uuid,
            action varchar(100) NOT NULL,
            entity_type varchar(100) NOT NULL DEFAULT '',
            entity_id varchar(64),
            old_state jsonb,
            new_state jsonb,
            ip_address inet,
            user_agent text NOT NULL,
            request_id uuid,
            source_system varchar(20) NOT NULL DEFAULT 'nbes',
            chain_hash varchar(64) NOT NULL,
            created_at timestamptz NOT NULL,
            PRIMARY KEY (id)
        );
    """)

    # 4. Recreate index/constraint on event_id
    schema_editor.execute("""
        CREATE UNIQUE INDEX audit_auditevent_event_id_key ON audit_auditevent (event_id);
    """)

    # 5. Recreate index on entity_id
    schema_editor.execute("""
        CREATE INDEX audit_auditevent_entity_id_idx ON audit_auditevent (entity_id);
    """)

    # 6. Copy data back
    schema_editor.execute("""
        INSERT INTO audit_auditevent (
            id, event_id, actor_id, action, entity_type, entity_id,
            old_state, new_state, ip_address, user_agent, request_id,
            source_system, chain_hash, created_at
        )
        SELECT
            id, event_id, actor_id, action, entity_type, entity_id,
            old_state, new_state, ip_address, user_agent, request_id,
            source_system, chain_hash, created_at
        FROM audit_auditevent_old;
    """)

    # 7. Align identity sequence
    schema_editor.execute("""
        SELECT setval(pg_get_serial_sequence('audit_auditevent', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM audit_auditevent;
    """)

    # 8. Drop old partitioned table
    schema_editor.execute("DROP TABLE audit_auditevent_old;")

    # 9. Recreate block mutations triggers on standard table
    schema_editor.execute("""
        CREATE TRIGGER audit_auditevent_no_update
        BEFORE UPDATE ON audit_auditevent
        FOR EACH ROW EXECUTE FUNCTION audit_auditevent_block_mutations();
    """)
    schema_editor.execute("""
        CREATE TRIGGER audit_auditevent_no_delete
        BEFORE DELETE ON audit_auditevent
        FOR EACH ROW EXECUTE FUNCTION audit_auditevent_block_mutations();
    """)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0008_alter_securityevent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="traceparent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="tracestate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.RunPython(
            partition_audit_event_postgresql,
            reverse_code=unpartition_audit_event_postgresql,
        ),
    ]
