# Generated by Django 6.0.5 on 2026-05-19 12:43

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('sitting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GracePeriodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15, unique=True)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=0)),
                ('late_surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resit_graceperiodconfig',
            },
        ),
        migrations.CreateModel(
            name='AttemptCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sitting_ref', models.CharField(blank=True, max_length=15, null=True)),
                ('exception_grants', models.JSONField(default=list)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_counters', to='registration.candidate')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_counters', to='sitting.subjectpaper')),
            ],
            options={
                'db_table': 'resit_attemptcounter',
                'unique_together': {('candidate', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='ExceptionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_by_id', models.UUIDField()),
                ('rationale', models.TextField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_ref', models.CharField(blank=True, max_length=50)),
                ('attempt_counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exception_records', to='resit.attemptcounter')),
            ],
            options={
                'db_table': 'resit_exceptiongrant',
            },
        ),
        migrations.CreateModel(
            name='ResitRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitting_ref', models.CharField(max_length=15)),
                ('status', django_fsm.FSMField(default='registered', max_length=50, protected=True)),
                ('fee_confirmed', models.BooleanField(default=False)),
                ('fee_reference', models.CharField(blank=True, max_length=100)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resit_registrations', to='registration.candidate')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resit_registrations', to='sitting.subjectpaper')),
            ],
            options={
                'db_table': 'resit_resitregistration',
            },
        ),
    ]
